---
- name: Requirements
  hosts: staging
  become: true
  become_user: root
  roles:
    - requirements

- name: Install Logstash
  hosts: staging
  become: true
  become_user: root
  roles:
    - logstash

- name: Install Beats
  hosts: staging
  become: true
  become_user: root
  roles:
    - beats
